effort_limit: 23.5
pinocchio_urdf: "/home/atari/workspace/DOOM/src/robots/go2/go2_description/urdf/go2_description.urdf"
xml_path: "/home/atari/workspace/DOOM/src/robots/go2/go2.xml"
stand_up_joint_pos:
  - 0.1
  - 0.8
  - -1.5
  - -0.1
  - 0.8
  - -1.5
  - 0.1
  - 1.0
  - -1.5
  - -0.1
  - 1.0
  - -1.5

stand_down_joint_pos:
  - 0.0473455
  - 1.22187
  - -2.44375
  - -0.0473455
  - 1.22187
  - -2.44375 
  - 0.0473455
  - 1.22187
  - -2.44375
  - -0.0473455
  - 1.22187
  - -2.44375

unitree_pin_joint_mappings: [ # [FR, FL, RR, RL] -> [FL, FR, RL, RR] or [FL, FR, RL, RR] -> [FR, FL, RR, RL]
  3,
  4,
  5,
  0,
  1,
  2,
  9,
  10,
  11,
  6,
  7,
  8,
]
