policy_path: "bimanual_g1/policy_smoothtorque.pt"
# policy_path: "bimanual_g1/policy_wristlocked_2.pt"
control_dt: 0.005
decimation: 4
action_dim: 14
# action_dim: 17
use_threading: False
use_buffer: False
device: "cuda:0"

horizon_length: 200
action_filter_alpha: 0.3
action_scale: 0.35 # 0.35
soft_dof_limit_factor: 0.9
standing_mode: true
# clip_actions: 5.0

# default_joint_pos: [
#                     -0.4500,  0.4000,  0.0000,  0.2000,  0.0000, 0.0000, -1.449,
#                     -0.4500, -0.4000,  0.0000,  0.2000,  0.0000,  0.0000, 1.449
#                     ]

default_joint_pos: [
                    # 0.0000,  0.0000,  0.0000,  
                    -0.4500,  0.4000,  0.0000,  0.2000,  0.0000, 0.0000, -1.449,
                    -0.4500, -0.4000,  0.0000,  0.2000,  0.0000,  0.0000, 1.449
                    ]
                    

visualize:
  object_pose: true
  contact_positions: true
  desired_object_pose: true
  ee_pose: false