# POLICY CONFIG
policy_path: "locomotion_go2/oliver/flatAmpVision/2025-08-12_14-23-30_flat_DR5_improved_minimal_motion_files_SEED_3/policy.pt"

control_dt: 0.002
decimation: 1
action_dim: 12
action_scale: 0.25
stiffness: 27.0
damping: 1.5

# PROCESSING CONFIG
device: "cuda:0"
use_threading: True
use_buffer: True
obs_buffer_length: 5



# MISC CONFIG
ISAAC_LAB_DEFAULT_JOINT_POS: [
    0.1000, # 0
    -0.1000, # 1
    0.1000, # 2
    -0.1000, # 3
    0.8000, # 4
    0.8000, # 5
    1.0000, # 6
    1.0000, # 7
    -1.5000, # 8
    -1.5000, # 9
    -1.5000, # 10
    -1.5000, # 11
  ] # from asset.data.default_joint_pos; corresponds to ISAACLAB_JOINT_ORDER; is used as action offset