policy_path: "policies/policy.pt"
control_dt: 0.002
action_dim: 12
action_scale: 
stiffness: 25.0
damping: 0.5
default_joint_pos:
  - 0.1
  - 0.8
  - -1.5
  - -0.1
  - 0.8
  - -1.5
  - 0.1
  - 1.0
  - -1.5
  - -0.1
  - 1.0
  - -1.5
state_keys: ['joint_pos']
