# POLICY CONFIG
policy_path: "locomotion_go2/velocity_policy_unidirectional.pt"

control_dt: 0.001
decimation: 4
action_dim: 12
action_scale: 0.35
stiffness: 25.0
damping: 0.5

# PROCESSING CONFIG
device: "cuda:0"
use_threading: False


# MISC CONFIG
ISAAC_LAB_DEFAULT_JOINT_POS: [
    0.1000, # 0
    -0.1000, # 1
    0.1000, # 2
    -0.1000, # 3
    0.8000, # 4
    0.8000, # 5
    1.0000, # 6
    1.0000, # 7
    -1.5000, # 8
    -1.5000, # 9
    -1.5000, # 10
    -1.5000, # 11
  ] # from asset.data.default_joint_pos; corresponds to ISAACLAB_JOINT_ORDER; is used as action offset