policy_path: "src/controllers/policies/IsaacLab policies/torqueComplexReward/TORQUE_complex_reward_10_SEED_42/policy.pt"
# For flat use src/controllers/policies/IsaacLab policies/flatAmpVision/2025-08-25_11-09-21_flat_DR5_improved_minimal_motion_files_lessTaskRewardLerp_SEED_1 and src/controllers/policies/IsaacLab policies/flatAmpVision/2025-08-12_14-23-30_flat_DR5_improved_minimal_motion_files_SEED_3
obs_dim: 51 # 51 for box, 48 for flat and standing w/ vicon
control_dt: 0.001
decimation: 1
SIMULATION_DT: 0.001
action_dim: 12
action_scale: 0.25
stiffness: 27.0 # 25
damping: 1.5 # 1.5


# for Torque
# obs_dim: 48 # 51 for box, 48 for flat and standing w/ vicon
# control_dt: 0.01
# decimation: 1
# SIMULATION_DT: 0.01
# action_dim: 12
# action_scale: 7.0
# stiffness: 0.0 # 25
# damping: 0.0 # 1.5
# action_filter_alpha: 1.0



# for BOX:
# obs_dim: 51
# control_dt: 0.001
# decimation: 1
# SIMULATION_DT: 0.001
# action_dim: 12
# action_scale: 0.27
# stiffness: 27.0 # 25
# damping: 1.5 # 1.5

# for STANDING
# control_dt: 0.001
# decimation: 1
# SIMULATION_DT: 0.001
# action_dim: 12
# action_scale: 0.25
# stiffness: 27.0 # 25
# damping: 1.5 # 1.5
default_joint_pos:
  - 0.1
  - 0.8
  - -1.5
  - -0.1
  - 0.8
  - -1.5
  - 0.1
  - 1.0
  - -1.5
  - -0.1
  - 1.0
  - -1.5

ISAACLAB_JOINT_ORDER: # breadth-first order, obtained from Aritculation.data.joint_names object
  - "FL_hip_joint" # 0
  - "FR_hip_joint" # 1
  - "RL_hip_joint" # 2
  - "RR_hip_joint" # 3
  - "FL_thigh_joint" # 4
  - "FR_thigh_joint" # 5
  - "RL_thigh_joint" # 6
  - "RR_thigh_joint" # 7
  - "FL_calf_joint" # 8
  - "FR_calf_joint" # 9
  - "RL_calf_joint" # 10
  - "RR_calf_joint" # 11

JOINT_OBSERVATION_UNITREE_TO_ISAAC_LAB_MAPPING:
  [3, 0, 9, 6, 4, 1, 10, 7, 5, 2, 11, 8]
JOINT_ACTION_ISAAC_LAB_TO_UNITREE_MAPPING:
  [1, 5, 9, 0, 4, 8, 3, 7, 11, 2, 6, 10]

ISAAC_LAB_DEFAULT_JOINT_POS: [
    0.1000, # 0
    -0.1000, # 1
    0.1000, # 2
    -0.1000, # 3
    0.8000, # 4
    0.8000, # 5
    1.0000, # 6
    1.0000, # 7
    -1.5000, # 8
    -1.5000, # 9
    -1.5000, # 10
    -1.5000, # 11
  ] # from asset.data.default_joint_pos; corresponds to ISAACLAB_JOINT_ORDER; is used as action offset
