from abc import ABC, abstractmethod

class RobotInterfaceBase(ABC):
    @abstractmethod
    def send_command(self, command):
        """
        Send a control command to the robot.

        Args:
            command (dict): Command generated by the controller.
        """
        pass

    @abstractmethod
    def receive_state(self):
        """
        Receive the current state of the robot/environment.

        Returns:
            dict: Current state of the robot/environment.
        """
        pass