ROBOT: "go2"
consts: robots/go2/consts.yaml

SIMULATION_DT: 0.005
VIEWER_DT: 0.02  # 50 fps for viewer
USE_JOYSTICK: 1
JOYSTICK_DEVICE: 0 # Joystick number
JOYSTICK_TYPE: "xbox"
PRINT_SCENE_INFORMATION: True
INTERFACE: "lo"
DOMAIN_ID: 1

model_path: "path/to/mujoco/model.xml"
time_step: 0.005
render: true
gravity: [0, 0, -9.8]
