"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: vicon_receiver.msg
  IDL file: ViconReceiver.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import vicon_receiver


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Position(idl.IdlStruct, typename="vicon_receiver.msg.Position"):
    x_trans: types.float32
    y_trans: types.float32
    z_trans: types.float32
    x_rot: types.float32
    y_rot: types.float32
    z_rot: types.float32
    w: types.float32
    segment_name: str
    subject_name: str
    frame_number: types.int32
    translation_type: str
