name: ATARI DOOM Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Initialize and update submodules
          token: ${{ secrets.GH_PAT }}  # Use the secret for authentication

      - name: Checkout specific branch for submodule
        run: |
          cd unitree_mujoco_container
          git fetch origin doom
          git checkout doom
          git pull origin doom

      - name: Build Docker Image
        run: docker build unitree_mujoco_container/.devcontainer/. --tag mujuni-image:$(date +%s)
