name: ATARI DOOM Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}

      - name: Initialize submodule and checkout doom branch
        run: |
          git submodule update --init --recursive
          cd unitree_mujoco_container
          git fetch origin
          git checkout -b doom origin/doom

      - name: Build Docker Image
        run: docker build unitree_mujoco_container/.devcontainer/. --tag mujuni-image:$(date +%s)
